### ISSUE TITLE
推荐添加`cross-env`支持Windows用户

### ISSUE THREAD

**Issue by monoplasty** [naihe138/nvue#1]
你好， 我是Windows用户。
1、项目下载下来之后。安装完依赖后运行 
`npm run dev`
会出现报错现象。 `NODE_ENV不是内部或外部命令`
故推荐安装依赖 `cross-env`
2、 项目目录少了static目录， 运行时`copy-webpack-plugin` 此插件会报错。
因为 `webpack.dev.config` 文件第108行
```
new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../static'),
        to: config.dev.assetsSubDirectory,
        ignore: ['.*']
      }
    ])
```
这里需要 `static`目录

**Comment by naihe138** [comment]
谢谢您，已经添加了
