### ISSUE TITLE
一个路径bug

### ISSUE THREAD

**Issue by Sliect** [naihe138/nvue#3]
我也尝试不用vue-cli 自己搭脚手架
但是引用element-ui时, 发现fonts的打包路径有问题, 尝试了你的模板是没问题的, 但是看不出问题在哪
仓库地址在 https://github.com/Sliect/webpack-path

谢谢!!!!

**Comment by Sliect** [comment]
有人在吗!!!

**Comment by naihe138** [comment]
看看 是不是 `outputPath: 'fonts/'`的问题

**Comment by Sliect** [comment]
并不是这个原因, 不管加不加上outputPath， 输出路径永远都是多一个css/层级
实际输出路径fonts, 请求路径css/fonts

**Comment by naihe138** [comment]
@Sliect  试试 `outputPath: "../fonts/",`

**Comment by Sliect** [comment]
试过了, 还是一样的

**Comment by naihe138** [comment]
或者 `outputPath: "./fonts/",` @Sliect

**Comment by Sliect** [comment]
最神奇的是图片输出路径没问题,

**Comment by Sliect** [comment]
./fonts也不行

**Comment by naihe138** [comment]
你应该在服务环境下运行

**Comment by Sliect** [comment]
嗯, 是在localhost 下运行的

**Comment by Sliect** [comment]
能抽空clone仓库看下么

**Comment by naihe138** [comment]
````

{
        test: /.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      }

````

你参考下

**Comment by Sliect** [comment]
这是一种办法, 但是超出limit，文件仍然404, 而且我好奇的是自己的写法和你的写法区别究竟在哪。一摸一样的输出写法, 在你的配置环境下是可以正常找到的

**Comment by Sliect** [comment]
new MiniCssExtractPlugin({
      filename: "css/[name].[hash].css"
 }),
中的路径css/ 去掉的话, 又是能正常显示
你的项目里测试过不管去不去掉都能正常显示

**Comment by Sliect** [comment]
一脸黑人问号, webpack 简直黑魔法

**Comment by naihe138** [comment]
这个是webpack4的压缩抽离 css文件的插件，多看看文档就阔以啦 ，我去上班啦

**Comment by Sliect** [comment]
插件文档看过很多遍了, 就差去读源码了
嗯，那我自己再找找看
