### ISSUE TITLE
ValidationError: Progress Plugin Invalid Options

### ISSUE THREAD

**Issue by umeitime** [naihe138/nvue#4]
ValidationError: Progress Plugin Invalid Options
build的时候出错了。

**Comment by AABig** [comment]
> Ok so the only thing that fixed this issue was to add this specific version of webpack as dev dependency.
> "webpack": "4.24.0"
升级到这个版本就对了，不要旧的，不要新的，就这个！
`npm install webpack@4.24.0 --save-dev`

**Comment by naihe138** [comment]
已经升级到最新版本的webapck 4.33.0 @AABig  @umeitime
